post:
  - Ctrl::User::&create
  - Ctrl::User::&request-token
  - Ctrl::User::&remove-tokens
  - Ctrl::Package::&available
get:
  - Ctrl::Package::&available
get:
  - Ctrl::UI::&main
  - Ctrl::UI::&try-static
