post:
  - Ctrl::User::&create
  - Ctrl::User::&request-token
  - Ctrl::User::&remove-tokens
  - Ctrl::Package::&candidates
  - Ctrl::Package::&dependencies
get:
  - Ctrl::Package::&candidates
get:
  - Ctrl::UI::&main
  - Ctrl::UI::&try-static
